### PR TITLE
Closes #23

### LINKED ISSUE #23: Expected Product (EXPTPROD)

### PR DESCRIPTION
**Pull request by ankitksh81**
Closes #23

### CODE REVIEW

**Comment by aryamasinha** [comment]
Please refer the CONTRIBUTING.md file.

**Comment by ankitksh81** [comment]
Okay I'll the screenshots also in all three PRs that I created.

**Comment by ankitksh81** [comment]
@aryamasinha, is it Okay if I add the screenshot of the question solved here in the comments ?

**Comment by aryamasinha** [comment]
Please refer the CONTRIBUTING.md file

**Comment by aryamasinha** [comment]
Yes

**Comment by ankitksh81** [comment]
Screenshot_2020-10-01 CodeChef Programming Competition,Programming Contest,Online Computer Programming

**Pull request merged**
